from toontown.coghq.SpecImports import *
GlobalEntities = {1000: {'type': 'levelMgr',
        'name': 'LevelMgr',
        'comment': '',
        'parentEntId': 0,
        'cogLevel': 0,
        'farPlaneDistance': 1500,
        'modelFilename': 'phase_12/models/bossbotHQ/BossbotEntranceRoom',
        'wantDoors': 1},
 0: {'type': 'zone',
     'name': 'UberZone',
     'comment': '',
     'parentEntId': 0,
     'scale': 1,
     'description': '',
     'visibility': []},
 10000: {'type': 'entrancePoint',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0, 6, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1,
         'entranceId': 0,
         'radius': 15,
         'theta': 20},
 100011: {'type': 'nodepath',
          'name': 'copy of camera3 target (2)',
          'comment': '',
          'parentEntId': 0,
          'pos': Point3(11, 11, 0.025),
          'hpr': Vec3(0, 0, 0),
          'scale': 1},
 100012: {'type': 'nodepath',
          'name': 'copy of camera3 target (2)',
          'comment': '',
          'parentEntId': 0,
          'pos': Point3(25, 2, 0.025),
          'hpr': Vec3(0, 0, 0),
          'scale': 1},
 120011: {'type': 'nodepath',
          'name': 'copy of camera3 target (2)',
          'comment': '',
          'parentEntId': 0,
          'pos': Point3(12, -2, 0.025),
          'hpr': Vec3(0, 0, 0),
          'scale': 1},
 120012: {'type': 'nodepath',
          'name': 'copy of camera3 target (2)',
          'comment': '',
          'parentEntId': 0,
          'pos': Point3(-12, 0.5, 0.025),
          'hpr': Vec3(0, 0, 0),
          'scale': 1},
 100014: {'type': 'securityCamera',
          'name': '<unnamed>',
          'comment': '',
          'parentEntId': 0,
          'pos': Point3(33.5, 10, 0.025),
          'hpr': Vec3(0, 0, 0),
          'scale': 1,
          'accel': 10.0,
          'damPow': 8,
          'hideModel': 0,
          'maxVel': 30.0,
          'modelPath': 0,
          'projector': Point3(0, 0, 20),
          'radius': 7.0,
          'switchId': 0,
          'trackTarget1': 100011,
          'trackTarget2': 100012,
          'trackTarget3': 0},
100015: {'type': 'securityCamera',
          'name': '<unnamed>',
          'comment': '',
          'parentEntId': 0,
          'pos': Point3(30.4, -9.8, 0.025),
          'hpr': Vec3(0, 0, 0),
          'scale': 1,
          'accel': 10.0,
          'damPow': 8,
          'hideModel': 0,
          'maxVel': 30.0,
          'modelPath': 0,
          'projector': Point3(0, 0, 20),
          'radius': 7.0,
          'switchId': 0,
          'trackTarget1': 120011,
          'trackTarget2': 120012,
          'trackTarget3': 0},
 110600: {'type': 'battleBlocker',
          'name': '<unnamed>',
          'comment': '',
          'parentEntId': 0,
          'pos': Point3(8.046, -30.702, 0),
          'hpr': Point3(270, 0, 0),
          'scale': Vec3(1, 1, 1),
          'cellId': 0,
          'radius': 10},
 10041: {'type': 'gagBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(-38.347, -18.963, 0.0),
         'hpr': Vec3(90.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0),
         'gagLevel': 7,
         'gagLevelMax': 0,
         'gagTrack': 'random',
         'rewardPerGrab': 4,
         'rewardPerGrabMax': 6},
 10042: {'type': 'gagBarrel',
         'name': '<unnamed>',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(-38.347, -10.548, 0.0),
         'hpr': Vec3(90.0, 0.0, 0.0),
         'scale': Vec3(1.0, 1.0, 1.0),
         'gagLevel': 7,
         'gagLevelMax': 0,
         'gagTrack': 'random',
         'rewardPerGrab': 4,
         'rewardPerGrabMax': 6},
 10002: {'type': 'nodepath',
         'name': 'props',
         'comment': '',
         'parentEntId': 0,
         'pos': Point3(0, 0, 0),
         'hpr': Vec3(0, 0, 0),
         'scale': 1}}
Scenario0 = {}
levelSpec = {'globalEntities': GlobalEntities,
 'scenarios': [Scenario0]}
