import random

from SpecImports import *
from toontown.toonbase import ToontownGlobals

CogParent = 110200
CogParent1 = 110600
CogParent2 = 110700
BattleCellId = 0
Battle1CellId = 1
Battle2CellId = 2
BattleCells = {BattleCellId: {'parentEntId': CogParent,
                              'pos': Point3(0, 0, 0)},
               Battle1CellId: {'parentEntId': CogParent1,
                               'pos': Point3(0, 0, 0)},
               Battle2CellId: {'parentEntId': CogParent2,
                               'pos': Point3(0, 0, 0)}}
CogData = [{'parentEntId': CogParent,
            'boss': 0,
            'level': ToontownGlobals.BossbotCountryClubSkelecogLevel,
            'battleCell': BattleCellId,
            'pos': Point3(-6, 0, 0),
            'h': 180,
            'behavior': 'stand',
            'path': None,
            'skeleton': 1},
           {'parentEntId': CogParent,
            'boss': 0,
            'level': ToontownGlobals.BossbotCountryClubCogLevel,
            'battleCell': BattleCellId,
            'pos': Point3(-2, 0, 0),
            'h': 180,
            'behavior': 'stand',
            'path': None,
            'skeleton': 0},
           {'parentEntId': CogParent,
            'boss': 0,
            'level': ToontownGlobals.BossbotCountryClubCogLevel,
            'battleCell': BattleCellId,
            'pos': Point3(2, 0, 0),
            'h': 180,
            'behavior': 'stand',
            'path': None,
            'skeleton': 0},
           {'parentEntId': CogParent,
            'boss': 0,
            'level': ToontownGlobals.BossbotCountryClubSkelecogLevel,
            'battleCell': BattleCellId,
            'pos': Point3(6, 0, 0),
            'h': 180,
            'behavior': 'stand',
            'path': None,
            'skeleton': 1},
           {'parentEntId': CogParent1,
            'boss': 0,
            'level': random.choice([7, 8]),
            'battleCell': Battle1CellId,
            'pos': Point3(-6, 0, 0),
            'h': 180,
            'behavior': 'stand',
            'path': None,
            'skeleton': random.choice([0, 1])},
           {'parentEntId': CogParent1,
            'boss': 0,
            'level': random.choice([7, 8]),
            'battleCell': Battle1CellId,
            'pos': Point3(-2, 0, 0),
            'h': 180,
            'behavior': 'stand',
            'path': None,
            'skeleton': random.choice([0, 1])},
           {'parentEntId': CogParent1,
            'boss': 0,
            'level': random.choice([7, 8]),
            'battleCell': Battle1CellId,
            'pos': Point3(2, 0, 0),
            'h': 180,
            'behavior': 'stand',
            'path': None,
            'skeleton': random.choice([0, 1])},
           {'parentEntId': CogParent1,
            'boss': 0,
            'level': random.choice([7, 8]),
            'battleCell': Battle1CellId,
            'pos': Point3(6, 0, 0),
            'h': 180,
            'behavior': 'stand',
            'path': None,
            'skeleton': random.choice([0, 1])},
           {'parentEntId': CogParent2,
            'boss': 0,
            'level': random.choice([7, 8]),
            'battleCell': Battle2CellId,
            'pos': Point3(-6, 0, 0),
            'h': 180,
            'behavior': 'stand',
            'path': None,
            'skeleton': random.choice([0, 1])},
           {'parentEntId': CogParent2,
            'boss': 0,
            'level': random.choice([7, 8]),
            'battleCell': Battle2CellId,
            'pos': Point3(-2, 0, 0),
            'h': 180,
            'behavior': 'stand',
            'path': None,
            'skeleton': random.choice([0, 1])},
           {'parentEntId': CogParent2,
            'boss': 0,
            'level': random.choice([7, 8]),
            'battleCell': Battle2CellId,
            'pos': Point3(2, 0, 0),
            'h': 180,
            'behavior': 'stand',
            'path': None,
            'skeleton': random.choice([0, 1])},
           {'parentEntId': CogParent2,
            'boss': 0,
            'level': random.choice([7, 8]),
            'battleCell': Battle2CellId,
            'pos': Point3(6, 0, 0),
            'h': 180,
            'behavior': 'stand',
            'path': None,
            'skeleton': random.choice([0, 1])}]
ReserveCogData = []
