TOON_STATUS_EFFECT = 0
SUIT_STATUS_EFFECT = 1

DAMAGE_UP = 0
DAMAGE_DOWN = 1
HEAL = 2
DAMAGE = 3
EXTRA_ATTACK = 4
DODGE_RATE = 5
ACCURACY_BOOST = 6
ACCURACY_DECREASE = 7
SPEED_UP = 8
SPEED_DOWN = 9
NO_ATTACKS_ALLOWED = 10

STATUS_EFFECT_NAME = 0
STATUS_EFFECT_BASER = 1
STATUS_EFFECT_VALUE = 2
STATUS_EFFECT_ROUNDS = 3
STATUS_EFFECT_INFINITE = 4
STATUS_EFFECT_EXTRA_ARGS = 5

WORKERS_MANAGEMENT = 'WorkersManagement'
